import { AsyncLocalStorage } from "node:async_hooks";
import { Pool, type PoolClient, types } from "pg";

/**
 * Banco Postgres (Supabase). A API imita a antiga versão SQLite — all/get/run/tx
 * com placeholders "?" — mas agora é assíncrona e os dados moram na nuvem,
 * compartilhados entre todos os computadores da loja.
 *
 * Datas continuam como TEXT ISO (YYYY-MM-DD...), valores em centavos (INTEGER),
 * exatamente como o app sempre tratou.
 */

// COUNT/SUM voltam como número (por padrão o driver devolveria string)
types.setTypeParser(20, (v) => parseInt(v, 10)); // BIGINT
types.setTypeParser(1700, (v) => parseFloat(v)); // NUMERIC

const SCHEMA = `
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS vehicles (
  id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  brand        TEXT NOT NULL,
  model        TEXT NOT NULL,
  version      TEXT,
  year_fab     INTEGER,
  year_model   INTEGER,
  plate        TEXT,
  km           INTEGER,
  color        TEXT,
  fuel         TEXT,
  transmission TEXT,
  renavam      TEXT,
  chassis      TEXT,
  laudo        TEXT,
  blindado     INTEGER,
  leilao       TEXT,
  fipe_price   INTEGER,
  consignado   INTEGER NOT NULL DEFAULT 0,
  consignor    TEXT,
  consignor_value INTEGER,
  consignado_date TEXT,
  origin_cpf      TEXT,
  origin_whatsapp TEXT,
  origin_email    TEXT,
  status       TEXT NOT NULL DEFAULT 'para_arrumar',
  sale_price   INTEGER,
  photo        TEXT,
  notes        TEXT,
  is_demo      INTEGER NOT NULL DEFAULT 0,
  created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS purchases (
  id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vehicle_id     INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  seller         TEXT,
  date           TEXT NOT NULL,
  price          INTEGER NOT NULL,
  payment_method TEXT,
  notes          TEXT,
  is_demo        INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS costs (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vehicle_id  INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  category    TEXT NOT NULL,
  description TEXT,
  amount      INTEGER NOT NULL,
  date        TEXT NOT NULL,
  is_demo     INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS customers (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name       TEXT NOT NULL,
  cpf_cnpj   TEXT,
  phone      TEXT,
  email      TEXT,
  city       TEXT,
  notes      TEXT,
  kind       TEXT NOT NULL DEFAULT 'comprador',
  status     TEXT NOT NULL DEFAULT 'novo',
  is_demo    INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS sellers (
  id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name             TEXT NOT NULL,
  commission_pct   REAL,
  commission_fixed INTEGER,
  created_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS deals (
  id                 INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vehicle_id         INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  customer_id        INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  stage              TEXT NOT NULL DEFAULT 'interessado',
  proposed_price     INTEGER,
  sale_price         INTEGER,
  down_payment       INTEGER,
  payment_method     TEXT,
  financed_amount    INTEGER,
  trade_in_desc      TEXT,
  trade_in_value     INTEGER,
  commission         INTEGER,
  commission_cost_id INTEGER,
  seller_id          INTEGER REFERENCES sellers(id),
  channel            TEXT,
  notes              TEXT,
  sold_date          TEXT,
  delivered_date     TEXT,
  is_demo            INTEGER NOT NULL DEFAULT 0,
  created_at         TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS tasks (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vehicle_id  INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,
  description TEXT,
  assignee    TEXT,
  due_date    TEXT,
  status      TEXT NOT NULL DEFAULT 'pendente',
  cost        INTEGER,
  cost_id     INTEGER,
  done_date   TEXT,
  is_demo     INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS documents (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name        TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'outro',
  vehicle_id  INTEGER REFERENCES vehicles(id) ON DELETE CASCADE,
  customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
  deal_id     INTEGER REFERENCES deals(id) ON DELETE SET NULL,
  purchase_id INTEGER REFERENCES purchases(id) ON DELETE SET NULL,
  file_name   TEXT NOT NULL,
  mime        TEXT,
  size        INTEGER,
  is_demo     INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS payables (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  description TEXT NOT NULL,
  category    TEXT,
  amount      INTEGER NOT NULL,
  due_date    TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'pendente',
  paid_date   TEXT,
  vehicle_id  INTEGER REFERENCES vehicles(id) ON DELETE SET NULL,
  is_demo     INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS receivables (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  description   TEXT NOT NULL,
  customer_id   INTEGER REFERENCES customers(id) ON DELETE SET NULL,
  deal_id       INTEGER REFERENCES deals(id) ON DELETE CASCADE,
  amount        INTEGER NOT NULL,
  due_date      TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pendente',
  received_date TEXT,
  is_demo       INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS events (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vehicle_id  INTEGER REFERENCES vehicles(id) ON DELETE CASCADE,
  customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
  deal_id     INTEGER REFERENCES deals(id) ON DELETE SET NULL,
  type        TEXT NOT NULL,
  description TEXT NOT NULL,
  amount      INTEGER,
  date        TEXT NOT NULL,
  is_demo     INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS vehicle_platforms (
  vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  platform   TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (vehicle_id, platform)
);

CREATE TABLE IF NOT EXISTS plate_lookups (
  plate      TEXT PRIMARY KEY,
  data       TEXT NOT NULL,
  brand      TEXT,
  model      TEXT,
  version    TEXT,
  year_fab   INTEGER,
  year_model INTEGER,
  color      TEXT,
  fuel       TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  token_hash TEXT PRIMARY KEY,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'America/Sao_Paulo', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS commission_rules (
  key    TEXT PRIMARY KEY,
  label  TEXT NOT NULL,
  amount INTEGER,
  sort   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_purchases_vehicle  ON purchases(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_costs_vehicle      ON costs(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_deals_vehicle      ON deals(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_deals_customer     ON deals(customer_id);
CREATE INDEX IF NOT EXISTS idx_tasks_vehicle      ON tasks(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_docs_vehicle       ON documents(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_receivables_deal   ON receivables(deal_id);
CREATE INDEX IF NOT EXISTS idx_events_vehicle     ON events(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_events_customer    ON events(customer_id);

INSERT INTO commission_rules (key, label, amount, sort) VALUES
  ('venda_carro', 'Venda de carro', 35000, 1),
  ('documentacao', 'Documentação', 2000, 2),
  ('financiamento', 'Financiamento', 5000, 3),
  ('venda_moto', 'Venda de moto', 25000, 4),
  ('venda_caminhao', 'Venda de caminhão', 50000, 5),
  ('outros', 'Outros', NULL, 6)
ON CONFLICT (key) DO NOTHING;

INSERT INTO meta (key, value) VALUES ('demo_seeded', '1') ON CONFLICT (key) DO NOTHING;

-- colunas novas em bancos já criados (idempotente)
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS consignado_date TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS origin_cpf TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS origin_whatsapp TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS origin_email TEXT;
`;

declare global {
  // Singletons por processo (sobrevivem ao hot reload do Next em dev).
  var __carosPool: Pool | undefined;
  var __carosReady: Promise<void> | undefined;
  var __carosTxStore: AsyncLocalStorage<PoolClient> | undefined;
}

function getPool(): Pool {
  if (!globalThis.__carosPool) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error("DATABASE_URL não configurada — crie o arquivo .env.local (veja o README).");
    globalThis.__carosPool = new Pool({
      connectionString: url,
      ssl: { rejectUnauthorized: false },
      max: 5,
    });
    // conexão ociosa que cair (comum em serverless) é descartada sem derrubar o processo
    globalThis.__carosPool.on("error", (e) => console.error("[db] conexão ociosa caiu:", e.message));
  }
  return globalThis.__carosPool;
}

const txStore = (globalThis.__carosTxStore ??= new AsyncLocalStorage<PoolClient>());

/** Garante que o schema existe (roda uma vez por processo; falha transitória tenta de novo). */
function ensureReady(): Promise<void> {
  if (!globalThis.__carosReady) {
    globalThis.__carosReady = getPool()
      .query(SCHEMA)
      .then(() => undefined)
      .catch((e) => {
        globalThis.__carosReady = undefined; // não envenena o processo: próxima requisição tenta de novo
        throw e;
      });
  }
  return globalThis.__carosReady;
}

type Param = string | number | null;

/** Converte os placeholders "?" (estilo SQLite) para $1, $2… do Postgres. */
function toPg(sql: string): string {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

/** Tabelas sem coluna id (o run() não tenta RETURNING id nelas). */
const NO_ID_TABLES = new Set(["meta", "commission_rules", "vehicle_platforms", "plate_lookups", "auth_sessions"]);

async function query(sql: string, params: Param[]): Promise<{ rows: Record<string, unknown>[]; rowCount: number }> {
  await ensureReady();
  const client = txStore.getStore();
  const result = client ? await client.query(toPg(sql), params) : await getPool().query(toPg(sql), params);
  return { rows: result.rows as Record<string, unknown>[], rowCount: result.rowCount ?? 0 };
}

export async function all<T>(sql: string, ...params: Param[]): Promise<T[]> {
  return (await query(sql, params)).rows as T[];
}

export async function get<T>(sql: string, ...params: Param[]): Promise<T | undefined> {
  return (await query(sql, params)).rows[0] as T | undefined;
}

export async function run(sql: string, ...params: Param[]): Promise<{ changes: number; lastId: number }> {
  const insertMatch = /^\s*insert\s+into\s+([a-z_]+)/i.exec(sql);
  let finalSql = sql;
  if (insertMatch && !/returning/i.test(sql) && !NO_ID_TABLES.has(insertMatch[1].toLowerCase())) {
    finalSql = `${sql} RETURNING id`;
  }
  const r = await query(finalSql, params);
  return { changes: r.rowCount, lastId: Number((r.rows[0] as { id?: number } | undefined)?.id ?? 0) };
}

/** Transação: tudo dentro do callback roda na mesma conexão. */
export async function tx<T>(fn: () => Promise<T>): Promise<T> {
  await ensureReady();
  const client = await getPool().connect();
  try {
    await client.query("BEGIN");
    const result = await txStore.run(client, fn);
    await client.query("COMMIT");
    return result;
  } catch (e) {
    await client.query("ROLLBACK");
    throw e;
  } finally {
    client.release();
  }
}

/** Configurações simples em chave/valor (tabela meta). */
export async function getMeta(key: string): Promise<string | null> {
  const row = await get<{ value: string | null }>("SELECT value FROM meta WHERE key = ?", key);
  return row?.value ?? null;
}

export async function setMeta(key: string, value: string | null): Promise<void> {
  if (value == null) await run("DELETE FROM meta WHERE key = ?", key);
  else await run("INSERT INTO meta (key, value) VALUES (?, ?) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value", key, value);
}

/** Existe algum dado de demonstração? (controla o aviso na interface) */
export async function hasDemoData(): Promise<boolean> {
  const tables = ["vehicles", "customers", "payables", "receivables"];
  for (const t of tables) {
    const row = await get<{ n: number }>(`SELECT COUNT(*) AS n FROM ${t} WHERE is_demo = 1`);
    if (row && row.n > 0) return true;
  }
  return false;
}
